# Generated by Django 4.0.5 on 2022-06-05 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('color', models.CharField(default='#FF0000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250, unique=True)),
                ('tourament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournament')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macthes', to='tournament.stage', verbose_name='matches')),
                ('team_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='tournament.team', verbose_name='teamA')),
                ('team_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='tournament.team', verbose_name='teamB')),
            ],
        ),
    ]
