# Generated by Django 4.0.5 on 2022-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('CHESS', 'CHESS'), ('FOOTBALL', 'FOOTBALL'), ('BASKETBALL', 'BASKETBALL')], default='CHESS', max_length=100),
        ),
    ]
