# Generated by Django 4.0.5 on 2022-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_stages',
            field=models.IntegerField(default=0),
        ),
    ]
