# Generated by Django 4.0.5 on 2022-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_match_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_part',
        ),
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(default='stage', max_length=250),
        ),
    ]
