# Generated by Django 4.0.5 on 2022-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_stage_stage_part_stage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=3),
        ),
    ]
