# Generated by Django 4.0.5 on 2022-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_stage_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
