# Generated by Django 4.0.5 on 2022-06-08 19:42

from django.db import migrations, models
import tournament.validators.match


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[tournament.validators.match.JSONMatchSchemaValidator(limit_value={'properties': {'team_a': {'properties': {'score': {'type': 'integer'}, 'team_name': {'type': 'string'}}, 'type': 'object'}, 'team_b': {'properties': {'score': {'type': 'integer'}, 'team_name': {'type': 'string'}}, 'type': 'object'}}, 'required': ['team_a', 'team_b'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
