# Generated by Django 4.0.5 on 2022-06-12 17:32

from django.db import migrations, models
import tournament.validators.match


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_alter_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('START', 'START'), ('IN_PROGRESS', 'IN_PROGRESS'), ('END', 'END')], default='START', max_length=250),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('START', 'START'), ('IN_PROGRESS', 'IN_PROGRESS'), ('END', 'END')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[tournament.validators.match.JSONMatchSchemaValidator(limit_value={'properties': {'team_a': {'type': 'integer'}, 'team_b': {'type': 'integer'}}, 'required': ['team_a', 'team_b'], 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
    ]
